### ISSUE TITLE
Clicking create offer repeatedly generates mutliple offers

### ISSUE THREAD

**Issue by Xoeseko** [sdgsolutionspace/sdg-market-frontend#1]
Hi,

I just realized that if a user gets impatient with the waiting for a buy offer to be generated (with slow internet for example) and clicks multiple times multiple offers are generated... It is of course still a prototype but I imagine this could be really dangerous in an actual production environment with real money at play.

## Steps to reproduce : 

1. In auctions on the sdg market frontend
2. "View actions" -> "Buying offers" -> "New purchase offer"
3. Repeatedly click "Create Purchase offer"

## Actual Results
Multiple purchase offers are saved [for example](https://sdg-market.oniabsis.com/auctions/project/3). 

## Expected Results
Only one offer created even when multiple clicks or a possibility to delete offers 

I was able to reproduce this but only at a smaller scale than the provided example. My network connection being slow at that moment certainly helped both generate frustration and allowed me to do multiple clicks before the offers were saved. I suspect this is the same for sale offers and other similar functionalities. Although I wasn't able to test that.

**Comment by gilles-hemmerle** [comment]
This was fixed. Will install the new version in test server once all ticket will be closed
